// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBubKqJ5mT5aOb760S40lAoGjzeT5Pf3Ro',
    appId: '1:618222452701:web:31d6a366363aaf3c928034',
    messagingSenderId: '618222452701',
    projectId: 'uimanagnment',
    authDomain: 'uimanagnment.firebaseapp.com',
    storageBucket: 'uimanagnment.firebasestorage.app',
    measurementId: 'G-S0TJ6KZ7XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADMP8fRaxU6yWaytSX8jdw2zbM6Nda4Zg',
    appId: '1:618222452701:android:41fc130ac07af238928034',
    messagingSenderId: '618222452701',
    projectId: 'uimanagnment',
    storageBucket: 'uimanagnment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg4gcylkbEBA3plGT0sFR1tVGW5CU85Yc',
    appId: '1:618222452701:ios:e1c3f7aa966569bf928034',
    messagingSenderId: '618222452701',
    projectId: 'uimanagnment',
    storageBucket: 'uimanagnment.firebasestorage.app',
    iosClientId: '618222452701-1m924hip0pvi1du9tee203orqn3lftbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.uiManagnment',
  );
}
